backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)

from api.views import (
    UserViewSet,
    AvatarViewSet,
    DkpViewSet,
    AuctionViewSet,
    CharacterViewSet,
    EventViewSet,
)

router = DefaultRouter()
router.register('users', UserViewSet, basename='users')
router.register('avatars', AvatarViewSet, basename='avatars')
router.register('dkp', DkpViewSet, basename='dkp')
router.register('auctions', AuctionViewSet, basename='auctions')
router.register('characters', CharacterViewSet, basename='characters')
router.register('events', EventViewSet, basename='events')

api_urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
]

docs_urlpatterns = [
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path(
        'docs/',
        SpectacularSwaggerView.as_view(url_name='schema'),
        name='docs'
    ),
]

urlpatterns = [
    path('api/', include(api_urlpatterns)),
    path('api/', include(docs_urlpatterns)),
]

backend/dkp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from dkp.views import (
    login_page,
    closed_auction,
    dkp_table,
    auction,
    profile,
)
from website import settings

app_name = 'dkp'

urlpatterns = [
    path('login/', login_page, name='web_login'),
    path('profile/', profile, name='profile'),
    path('', dkp_table, name='home'),
    path('auction/', auction, name='auction'),
    path('closed-auctions/', closed_auction, name='closed_auction'),
    path(
        'logout/',
        LogoutView.as_view(template_name=settings.LOGIN_REDIRECT_URL),
        name='web_logout'
    ),
]

backend/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'dkp.views.page_not_found'
handler500 = 'dkp.views.internal_server_error'

urlpatterns = [
    path('', include('api.urls')),
    path('', include('dkp.urls', namespace='dkp')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/dkp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.constants import (
    GUILD_NAME_MAX_LENGTH,
    CHARACTER_MAX_LENGTH,
    EVENT_NAME_MAX_LENGTH,
    IS_ACTIVE_MAX_LENGTH,
    MOSCOW_TZ,
)
from core.validators import (
    validate_greater_than_zero,
    validate_close_date_greater_than_created_at,
)

User = get_user_model()


class Guild(models.Model):
    name = models.CharField(
        'Название гильдии', unique=True,
        max_length=GUILD_NAME_MAX_LENGTH,
    )
    description = models.TextField('Описание', null=True, blank=True)

    class Meta:
        verbose_name = 'гильдия'
        verbose_name_plural = 'Гильдии'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Character(models.Model):
    name = models.CharField(
        'Имя персонажа', unique=True,
        max_length=CHARACTER_MAX_LENGTH
    )
    guild = models.ForeignKey(
        Guild, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='guild_characters', verbose_name='Гильдия'
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='characters', verbose_name='Пользователь'
    )
    created_at = models.DateTimeField('Дата проведения', auto_now_add=True)

    class Meta:
        verbose_name = 'персонаж'
        verbose_name_plural = 'Персонажи'
        ordering = ('name',)

    def __str__(self):
        return self.name


class EventType(models.Model):
    name = models.CharField(
        'Наименование', unique=True,
        max_length=EVENT_NAME_MAX_LENGTH
    )
    cost = models.IntegerField(
        'Стоимость',
        validators=[
            validate_greater_than_zero,
        ]
    )
    description = models.TextField('Описание', null=True, blank=True)

    class Meta:
        verbose_name = 'тип события'
        verbose_name_plural = 'Типы событий'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Event(models.Model):

    class Status(models.TextChoices):
        ACTIVE = 'active', _('Активный')
        CLOSED = 'closed', _('Завершенный')

    event_type = models.ForeignKey(
        EventType, on_delete=models.CASCADE,
        related_name='event_types', verbose_name='Тип события'
    )
    created_at = models.DateTimeField('Дата проведения', auto_now_add=True)
    is_active = models.CharField(
        'Статус', max_length=IS_ACTIVE_MAX_LENGTH,
        choices=Status.choices, default=Status.ACTIVE,
    )

    class Meta:
        verbose_name = 'событие'
        verbose_name_plural = 'События'
        ordering = ('-created_at',)

    @property
    def local_created_at(self):
        return self.created_at.astimezone(MOSCOW_TZ)

    def __str__(self):
        formated_date = self.local_created_at.strftime('%H:%M %d.%m.%Y')
        return f'{self.event_type} {formated_date}'


class EventCharacter(models.Model):
    event_id = models.ForeignKey(
        Event, on_delete=models.CASCADE,
        related_name='events', verbose_name='Событие'
    )
    character = models.ForeignKey(
        Character, on_delete=models.CASCADE,
        related_name='event_characters', verbose_name='Персонаж'
    )

    class Meta:
        verbose_name = 'регистация в собитии'
        verbose_name_plural = 'Регистация в собитии'
        ordering = ('event_id',)


class Auction(models.Model):

    class Status(models.TextChoices):
        ACTIVE = 'active', _('Активный')
        CLOSED = 'closed', _('Завершенный')

    lot_image = models.ImageField('Изображение лота', upload_to='auctions/',)
    close_date = models.DateTimeField('Дата окончания')
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    is_active = models.CharField(
        'Статус', max_length=IS_ACTIVE_MAX_LENGTH,
        choices=Status.choices, default=Status.ACTIVE,
    )

    class Meta:
        verbose_name = 'аукцион'
        verbose_name_plural = 'Аукционы'
        ordering = ('-created_at',)

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)
        validate_close_date_greater_than_created_at(self.close_date, self)

    def __str__(self):
        formated_date = self.created_at.strftime('%H:%M %Y.%m.%d')
        return f'Аукцион №{self.id} от {formated_date}'


class Bet(models.Model):
    auction_id = models.ForeignKey(
        Auction, on_delete=models.CASCADE,
        related_name='auctions', verbose_name='Аукцион'
    )
    character = models.ForeignKey(
        Character, on_delete=models.CASCADE,
        related_name='bet_characters', verbose_name='Персонаж'
    )
    bet = models.IntegerField('Ставка')
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        verbose_name = 'ставка'
        verbose_name_plural = 'Ставки'
        ordering = ('-created_at',)

    def __str__(self):
        return f'Ставка пользователя {self.character.user.username}'

    @staticmethod
    def max_bets(auctions) -> dict[str, dict]:
        max_bets = {}
        for auction in auctions:
            max_bet = auction.auctions.order_by('-bet').first()
            max_bets['auction_id'] = {
                'character': max_bet.character,
                'bet': max_bet.bet
            }
        return max_bets


class Dkp(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='dkp_users', verbose_name='Имя пользователя'
    )
    character = models.ForeignKey(
        Character, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='dkp_characters', verbose_name='Имя персонажа'
    )
    points = models.IntegerField('Очки дкп', default=0)
    last_activity = models.DateTimeField('Дата последней активности')
    is_active = models.BooleanField('Активный аккаунт', default=True)
    description = models.TextField('Описание', null=True, blank=True)

    class Meta:
        verbose_name = 'DKP'
        verbose_name_plural = 'DKP'
        ordering = ('character__name',)

    def __str__(self):
        return f'DKP пользователя {self.user}'

backend/dkp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AuthorizationForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

backend/dkp/views.py
from http import HTTPStatus

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from core.constants import (
    HOME_URL,
    DKP_OBJECTS_ON_PAGE,
    LOT_OBJECTS_ON_PAGE,
)
from dkp.forms import RegistrationForm, AuthorizationForm
from dkp.utils import (
    get_dkp_table,
    get_event_types,
    get_event_and_players,
    create_new_event,
    register_for_event,
    close_event,
    delete_player_from_event,
    get_lots,
    get_closed_lots,
    create_new_lot,
    create_new_bet,
    get_paginate,
    get_user_events,
    get_base_context,
    require_character,
    auction_complete,
    edit_character_name,
)
from website import settings

POST_HANDLERS = {
    'create_event_submit': create_new_event,
    'event_registration_submit': register_for_event,
    'event_close_submit': close_event,
    'event_delete_user_submit': delete_player_from_event,
    'create_lot': create_new_lot,
    'create_bet_submit': create_new_bet,
}


def login_page(request):
    """Генерация страницы логина."""
    template = 'dkp/index.html'
    reg_form = None
    auth_form = None

    if request.method == 'POST':
        if 'reg_submit' in request.POST:
            reg_form = RegistrationForm(request.POST)
            if reg_form.is_valid():
                user = reg_form.save()
                login(request, user)
                return redirect(settings.LOGIN_REDIRECT_URL)
        elif 'auth_submit' in request.POST:
            auth_form = AuthorizationForm(request.POST)
            user = authenticate(
                username=request.POST['username'],
                password=request.POST['password']
            )
            if user is not None and user.is_active:
                login(request, user)
                return redirect(HOME_URL)
    else:
        reg_form = RegistrationForm()
        auth_form = AuthorizationForm()

    context = {
        'reg_form': reg_form,
        'auth_form': auth_form
    }
    return render(request, template, context)


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
def profile(request):
    """Генерация страницы профиля."""
    template = 'dkp/profile.html'
    character = request.user.characters.first()
    if request.method == 'POST':
        return edit_character_name(request)
    events = get_user_events(character)[:10] if character else None
    context = {
        'character': character,
        'events': events,
    }
    context.update(get_base_context(request))
    return render(request, template, context)


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@require_character
@auction_complete
def dkp_table(request):
    """Генерация домашней страницы."""
    template = 'dkp/dkp.html'
    if request.method == 'POST':
        handler = next(
            (
                POST_HANDLERS[key]
                for key in POST_HANDLERS
                if key in request.POST
            ),
            None
        )
        if handler:
            return handler(request)
    dkp_table = get_dkp_table()
    event, event_players = get_event_and_players()
    page_number = request.GET.get('page', 1)
    dkp_paginator = Paginator(dkp_table, DKP_OBJECTS_ON_PAGE)
    dkp_page_obj = get_paginate(dkp_paginator, page_number)
    context = {
        'paginator': dkp_paginator,
        'event_players': event_players,
        'dkp_table': dkp_page_obj,
        'event_types': get_event_types(),
        'event': event,
    }
    context.update(get_base_context(request))
    return render(request, template, context)


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@require_character
@auction_complete
def auction(request):
    """Генерация домашней страницы."""
    template = 'dkp/dkp.html'
    if request.method == 'POST':
        handler = next(
            (
                POST_HANDLERS[key]
                for key in POST_HANDLERS
                if key in request.POST
            ),
            None
        )
        if handler:
            return handler(request)
    lots = get_lots()
    page_number = request.GET.get('page', 1)
    lot_paginator = Paginator(lots, LOT_OBJECTS_ON_PAGE)
    lot_page_obj = get_paginate(lot_paginator, page_number)
    context = {
        'paginator': lot_paginator,
        'lots': lot_page_obj,
    }
    context.update(get_base_context(request))
    return render(request, template, context)


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@require_character
@auction_complete
def closed_auction(request):
    """Генерация домашней страницы."""
    template = 'dkp/dkp.html'
    lots = get_closed_lots()
    page_number = request.GET.get('page', 1)
    lot_paginator = Paginator(lots, LOT_OBJECTS_ON_PAGE)
    lot_page_obj = get_paginate(lot_paginator, page_number)
    context = {
        'paginator': lot_paginator,
        'lots': lot_page_obj,
    }
    context.update(get_base_context(request))
    return render(request, template, context)


def page_not_found(request, exception):
    return render(request, 'errors/404.html', status=HTTPStatus.NOT_FOUND)


def csrf_failure(request, reason=''):
    return render(request, 'errors/403csrf.html', status=HTTPStatus.FORBIDDEN)


def internal_server_error(request):
    return render(
        request, 'errors/500.html', status=HTTPStatus.INTERNAL_SERVER_ERROR
    )

backend/templates/dkp/dkp.html
{% extends "base.html" %}
{% block title %}
    <title>BLOODCULT DKP</title>
{% endblock %}
{% block content %}
    <main class="main main__dkp">
        <section class="dkp">
            <div class="container">
                <div class="dkp__inner tabs">
                    <ul class="tabs-nav">
                        <li><a href="{% url 'dkp:home' %}" {% if request.path == "/" %}class="active"{% endif %}>Последние начисления</a></li>
                        <li><a href="{% url 'dkp:auction' %}" {% if request.path == "/auction/" %}class="active"{% endif %}>Аукцион за DKP</a></li>
                        <li><a href="{% url 'dkp:closed_auction' %}" {% if request.path == "/closed-auctions/" %}class="active"{% endif %}>Завершенные аукционы</a></li>
                    </ul>
                    <div class="tabs-items">
                        {% if request.path == "/" %}
                            {% include "includes/table.html" with page=dkp_table %}
                        {% elif request.path == "/auction/" %}
                            {% include "includes/auction.html" with page=lots %}
                        {% else %}
                            {% include "includes/closed_auctions.html" with page=lots %}
                        {% endif %}    
                    </div>
                </div>
            </div>
        </section>
    </main>
    {% if request.path == "/" %}
        {% include "includes/create_event.html"%}
    {% else %}
    {% include "includes/create_lot.html" %}
        {% include "includes/bet.html" %}
    {% endif %}
{% endblock %}

backend/templates/dkp/index.html
{% extends "base.html" %}
{% block title %}
    <title>BLOODCULT</title>
{% endblock %}
{% block content %}
    <main>
        <div class="container py-5">
            <section class="intro">
                <div class="container">
                    <div class="intro__inner">
                        <a href="#" class="intro__btn callmodal" data-id="#popup-recall">ВОЙТИ</a>
                    </div>
                </div>
            </section>

            <div class="popup popup__main" style="display: none; width: 561px;" id="popup-recall">
                <div class="tabs" id="tabs">
                    <ul class="tabs-nav">
                        <li><a href="#tab-2" >Войти</a></li>
                        <li><a href="#tab-1" class="active" id="tab-1">Зарегистрироваться</a></li>
                    </ul>
                    <div class="tabs-items">
                        {% include "includes/registration.html" with form=reg_form %}
                        {% include "includes/authorization.html" with form=auth_form %}
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Скрипт для открытия модального окна при наличии ошибок -->
    <script>
        window.onload = function () {
            const regErrorsExist = '{{ reg_form.errors }}';
            const authErrorsExist = '{{ auth_form.errors }}';
            
            if (regErrorsExist.trim() || authErrorsExist.trim()) {
                $.fancybox.open({ src: '#popup-recall' });
                document.querySelector('#tab-1').click();
            }
        };
    </script>
{% endblock %}

backend/templates/dkp/profile.html
{% extends "base.html" %}
{% block title %}
    <title>Профиль пользователя</title>
{% endblock %}
{% block content %}
    <main class="main main__dkp">

    <section class="acc">
        <div class="container">
            <div class="acc__title">Профиль пользователя</div>
            {% if messages %}
                <div class="messages__box">
                    <div class="messages">
                        {% for message in messages %}
                        <div class="alert alert-error">
                            {{ message }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            <form class="acc__form" method="post" action=".">
                {% csrf_token %}
                <div class="acc__form-row">
                    {% if character %}
                        <div class="acc__form-item">
                            <input type="text" class="input__prem" name="character_name" placeholder="{{ character.name }}">
                        </div>
                        <div class="acc__form-item">
                            <button class="btn__prem">Переименовать</button>
                        </div>
                    {% else %}
                        <div class="acc__form-item">
                            <input type="text" class="input__prem" name="character_name" placeholder="Введите имя игрового персонажа">
                        </div>
                        <div class="acc__form-item">
                            <button class="btn__prem">Создать</button>
                        </div>
                    {% endif %}
                </div>
            </form>
            <div class="dkp__tabs">
                <div class="dkp__tabs-item dkp__tabs-title">
                    <div>Событие</div>
                    <div>Последние начисления</div>
                    <div>Дата</div>
                </div>
                
                <div class="dkp__tabs-inner">
                    {% for event in events %}
                        <div class="dkp__tabs-item">
                            <div>{{ event.event_type.name }}</div>
                            <div>+{{ event.event_type.cost }} DKP</div>
                            <div>{{ event.created_at }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

    </main>
{% endblock %}