backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)

from api.views import (
    UserViewSet,
    AvatarViewSet,
    DkpViewSet,
    AuctionViewSet,
    CharacterViewSet,
    EventViewSet,
)

router = DefaultRouter()
router.register('users', UserViewSet, basename='users')
router.register('avatars', AvatarViewSet, basename='avatars')
router.register('dkp', DkpViewSet, basename='dkp')
router.register('auctions', AuctionViewSet, basename='auctions')
router.register('characters', CharacterViewSet, basename='characters')
router.register('events', EventViewSet, basename='events')

api_urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
]

docs_urlpatterns = [
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path(
        'docs/',
        SpectacularSwaggerView.as_view(url_name='schema'),
        name='docs'
    ),
]

urlpatterns = [
    path('api/', include(api_urlpatterns)),
    path('api/', include(docs_urlpatterns)),
]

backend/dkp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from dkp.views import (
    login_page,
    closed_auction,
    dkp_table,
    auction,
    profile,
)
from website import settings

app_name = 'dkp'

urlpatterns = [
    path('login/', login_page, name='web_login'),
    path('profile/', profile, name='profile'),
    path('', dkp_table, name='home'),
    path('auction/', auction, name='auction'),
    path('closed-auctions/', closed_auction, name='closed_auction'),
    path(
        'logout/',
        LogoutView.as_view(template_name=settings.LOGIN_REDIRECT_URL),
        name='web_logout'
    ),
]

backend/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'dkp.views.page_not_found'
handler500 = 'dkp.views.internal_server_error'

urlpatterns = [
    path('', include('api.urls')),
    path('', include('dkp.urls', namespace='dkp')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/templates/includes/auction.html
{% load static %}
<div class="tabs-item" id="tab-2">
    <h2 class="dkp__title">Аукцион за DKP</h2>
        {% if messages %}
            <div class="messages__box">
                <div class="messages">
                    {% for message in messages %}
                    <div class="alert alert-error">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    <div class="dkp__auc">
        {% for lot in lots %}
            <div class="dkp__auc-item" data-close-date="{{ lot.close_date|date:'c' }}">
                <div class="dkp__auc-timer">
                    <span>До окончания аукциона: </span>
                    <div class="counter">
                        <div class="getting-started"></div>
                    </div>
                </div>
                <img src="{{ MEDIA_URL }}{{ lot.lot_image }}" alt="" class="dkp__auc-img">
                <div class="dkp__auc-name">
                    {% if lot.character %}
                        Последняя ставка: <span>{{ lot.character }} {{ lot.bet }} DKP</span>
                    {% else %}
                        Последняя ставка: <span>Ставок нет</span>
                    {% endif %}
                </div>
                <a href="#" class="btn__prem callmodal" data-id="#popup-auc" data-lot-id="{{ lot.id }}">Сделать ставку</a>
            </div>
        {% endfor %}
    </div>
    {% include "includes/pagination.html" %}
    {% if request.user.is_staff %}
        <div class="dkp__btn">
            <a href="#" class="intro__btn callmodal" data-id="#popup-luc">СОЗДАТЬ ЛОТ</a>
        </div>
    {% endif %}
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const counters = document.querySelectorAll('.counter');
    
        counters.forEach(counter => {
            const item = counter.closest('.dkp__auc-item');
            const closeDateStr = item.getAttribute('data-close-date');
            const closeDate = new Date(closeDateStr).getTime();
    
            function updateTimer() {
                const now = new Date().getTime();
    
                const diff = closeDate - now;
    
                if (diff > 0) {
                    let days = Math.floor(diff / (1000 * 60 * 60 * 24));
                    let hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)).toString().padStart(2, '0');
                    let minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60)).toString().padStart(2, '0');
                    let seconds = Math.floor((diff % (1000 * 60)) / 1000).toString().padStart(2, '0');
                    counter.innerHTML = `${hours}:${minutes}:${seconds}`;
                } else {
                    clearInterval(timerId);
                    counter.innerHTML = 'Аукцион завершен';
                }
            }
    
            const timerId = setInterval(updateTimer, 1000);
            updateTimer();
        });
    });
</script>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const buttons = document.querySelectorAll('.callmodal');
        
        buttons.forEach(button => {
            button.addEventListener('click', (event) => {
                event.preventDefault();
                
                const lotIdInput = document.getElementById('lot-id-input');
                const lotId = button.dataset.lotId;
                
                lotIdInput.value = lotId;
                
                const modalId = button.dataset.id;
                const modalElement = document.querySelector(modalId);
                modalElement.style.display = 'block';
            });
        });
    });
</script>

backend/templates/includes/authorization.html
<div class="tabs-item" id="tab-2">
    <div class="popup__title">Авторизоваться</div>
    <form class="popup__form" method="post" novalidate id="authorization-form">
        {% csrf_token %}
        <div class="popup__form-item">
            <input type="text" class="input__prem" name="username" placeholder="Введите свой никнейм">
            {% for error in auth_form.username.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="popup__form-item">
            <input type="password" class="input__prem" name="password" placeholder="Введите пароль">
            {% for error in auth_form.password.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="popup__form-item">
            <button class="btn__prem" type="submit" name="auth_submit">Авторизироваться</button>
        </div>
    </form>
</div>

backend/templates/includes/bet.html
<div class="popup popup__main" style="display: none; width: 361px;" id="popup-auc">
    <form class="popup__auc-form" method="POST">
        {% csrf_token %}
        <input type="hidden" name="lot_id" id="lot-id-input">
        <div class="popup__auc-form-item">
            <input type="text" name="new_bet" class="input__prem" placeholder="Сделайте ставку">
        </div>
        <div class="popup__auc-form-item">
            <button class="btn__prem" name="create_bet_submit">Сделать ставку</button>
        </div>
    </form>
</div>

backend/templates/includes/closed_auctions.html
{% load static %}
<div class="tabs-item" id="tab-3">
    <h2 class="dkp__title">Завершенные аукционы</h2>
    <div class="dkp__auc">
        {% for lot in lots %}
            <div class="dkp__auc-item">
                
                <div class="dkp__auc-name">
                    {% if lot.character %}
                        Победившая ставка: <span>{{ lot.character }} {{ lot.bet }} DKP</span>
                    {% else %}
                        Победившая ставка: <span>Никто не сделал ставку</span>
                    {% endif %}
                </div>
                <img src="{{ MEDIA_URL }}{{ lot.lot_image }}" alt="" class="dkp__auc-img">
            </div>
        {% endfor %}
    </div>
    {% include "includes/pagination.html" %}
</div>

backend/templates/includes/create_event.html
<div class="popup popup__main" style="display: none; width: 521px;" id="popup-luc-inner">
    <h2>Мероприятие</h2>
    <form class="popup__auc-form" method="post">
        {% csrf_token %}
        <div class="popup__auc-form-item">
            <select class="js-example-basic-single" name="event_type">
                {% for event in event_types %}
                    <option value="{{ event.id }}">{{ event.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="popup__auc-form-item">
            <button class="btn__prem" name="create_event_submit">Добавить</button>
        </div>
    </form>
</div>

backend/templates/includes/create_lot.html
<div class="popup popup__main" style="display: none; width: 521px;" id="popup-luc">
    <form class="popup__auc-form" name="create_lot" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="popup__auc-form-item">
            <div class="field__wrapper">
                <input type="file" name="file" id="field__file-2" class="field field__file" multiple>
                <label class="field__file-wrapper" for="field__file-2">
                    <div class="field__file-fake">Файл не вбран</div>
                    <div class="field__file-button">+</div>
                </label>
            </div>
        </div>
        <div class="popup__auc-form-item">
            <input name="time" type="time" class="input__prem">
        </div>
        <div class="popup__auc-form-item">
            <button class="btn__prem" name="create_lot">Добавить</button>
        </div>
    </form>
</div>

backend/templates/includes/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <div class="footer__inner">
            <div>©2024 ВСЕ ПРАВА ЗАЩИЩЕНЫ</div>
            <div class="header__social">
                <img src="{% static 'img/vk-icon.png' %}" alt="">
                <div class="header__social-des">
                    <p>Мы Вконтакте</p>
                    <a href="https://vk.com/bloodcult.clan">https://vk.com/bloodcult.clan</a>
                </div>
            </div>
            <a href="javascript:;" >политика конфендициальности</a>
        </div>
    </div>
</footer>

backend/templates/includes/header.html
{% load static %}
<header class="header">
    <div class="container">
        <div class="header__inner">
            <a href="/" class="header__logo">
                <img src="{% static 'img/logo.png' %}" alt="">
            </a>
            {% if user.is_authenticated %}
                <div class="header__acc">
                    <div class="header__avatar">
                        <div class="header__avatar-inner">
                            <img src="{{ MEDIA_URL }}{{ avatar.avatar }}" alt="">
                        </div>
                    </div>
                    <div>
                        <a href="{% url 'dkp:profile' %}" class="header__acc-name">{{ username }}</a>
                        <div>DKP: {{ dkp_points }} </div>
                        <div>
                            <form action="{% url 'dkp:web_logout' %}" method="post" class="header__logout-form">
                                {% csrf_token %}
                                <button type="submit" class="header__logout-button">Выход</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</header>

backend/templates/includes/pagination.html
{% if paginator.num_pages > 1 %}
    <div class="dkp__pag">
        {% for num in paginator.page_range %}
            {% if num == page.number %}
                <a href="#" class="dkp__pag-item active">{{ num }}</a>
            {% else %}
                <a href="?page={{ num }}" class="dkp__pag-item">{{ num }}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

backend/templates/includes/registration.html
<div class="tabs-item" id="tab-1">
    <div class="popup__title">Регистрация</div>
    <form class="popup__form" method="post" novalidate id="registration-form">
        {% csrf_token %}
        <div class="popup__form-item">
            <input type="text" class="input__prem" name="username" placeholder="Введите свой никнейм">
            {% for error in reg_form.username.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="popup__form-item">
            <input type="text" class="input__prem" name="email" placeholder="Введите свой E-mail">
            {% for error in reg_form.email.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="popup__form-item">
            <input type="password" class="input__prem" name="password1" placeholder="Введите пароль">
            {% for error in reg_form.password1.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="popup__form-item">
            <input type="password" class="input__prem" name="password2" placeholder="Повторите пароль">
            {% for error in reg_form.password2.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="popup__form-item">
            <button class="btn__prem" type="submit" name="reg_submit">Зарегистрироваться</button>
        </div>
        <div class="popup__form-item">
            <label class="main-form-checkbox">
                <span class="main-form-checkbox-text">
                    Нажимая на кнопку “Зарегистрироваться“ вы даёте согласие на обработку персональных данных
                </span>
                <input checked class="main-form-checkbox-input" type="checkbox">
                <span class="main-form-checkbox-checkmark"></span>
            </label>
        </div>
    </form>
</div>

backend/templates/includes/table.html
<div class="tabs-item" id="tab-1">
    <h2 class="dkp__title">Таблица DKP</h2>
    {% if event %}
        <div class="dkp__event">
            <div class="dkp__event-title">{{ event.event_type }}</div>
            <div class="dkp__event-btn">
                <form method="post" action=".">
                {% csrf_token %}
                    <button class="btn__item" name="event_registration_submit">Зарегистрироваться</button>
                    {% if request.user.is_staff %}
                        <button class="btn__prem" name="event_close_submit">Закрыть событие</button>
                    {% endif %}
                </form>
            </div>
            <div class="dkp__event-list">
                {% if event_players %}
                    {% for event_player in event_players%}
                        <div class="dkp__event-list-item">
                            <div>{{ forloop.counter }}. {{ event_player.character }}</div>
                            {% if request.user.is_staff %}
                                <form method="post" action=".">
                                    {% csrf_token %}
                                    <input type="hidden" name="player_id" value="{{ event_player.id }}">
                                    <button class="dkp__event-list-btn" name="event_delete_user_submit">Удалить</button>
                                </form>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    {% endif %}
    <div class="dkp__tabs">
        <div class="dkp__tabs-item dkp__tabs-title">
            <div>Имя персонажа</div>
            <div>Общее количество DKP</div>
            <div>Дата последнего участия</div>
        </div>
        <div class="dkp__tabs-inner">
            {% for player in dkp_table %}
                <div class="dkp__tabs-item">
                    <div>{{ player.character }}</div>
                    <div>{{ player.points }}</div>
                    <div>{{ player.last_activity }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% include "includes/pagination.html" %}
    {% if request.user.is_staff %}
        <div class="dkp__btn">
            <a href="#" class="intro__btn callmodal" data-id="#popup-luc-inner">СОЗДАТЬ МЕРОПРИЯТИЕ</a>
        </div>
    {% endif %}
</div>